In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
data=pd.read_csv('zomato.csv', encoding='latin-1')

In [4]:
data.head()

Restaurant ID         Restaurant Name  Country Code              City  \
0        6317637        Le Petit Souffle           162       Makati City   
1        6304287        Izakaya Kikufuji           162       Makati City   
2        6300002  Heat - Edsa Shangri-La           162  Mandaluyong City   
3        6318506                    Ooma           162  Mandaluyong City   
4        6314302             Sambo Kojin           162  Mandaluyong City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3  Third Floor, Mega Fashion Hall, SM Megamall, O...   
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...   

                                     Locality  \
0   Century City Mall, Poblacion, Makati City   
1  Little Tokyo, Legaspi Village, Makati City   
2  Edsa Shangri-La, Ortigas, Mandaluyong City   
3      SM Megamall, Ortigas, Mandaluyong City   
4      SM Megamall, Ortigas, Mandaluyong City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708   
2  Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404   
3  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475  14.585318   
4  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508  14.584450   

                           Cuisines  ...          Currency Has Table booking  \
0        French, Japanese, Desserts  ...  Botswana Pula(P)               Yes   
1                          Japanese  ...  Botswana Pula(P)               Yes   
2  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)               Yes   
3                   Japanese, Sushi  ...  Botswana Pula(P)                No   
4                  Japanese, Korean  ...  Botswana Pula(P)               Yes   

  Has Online delivery Is delivering now Switch to order menu Price range  \
0                  No                No                   No           3   
1                  No                No                   No           3   
2                  No                No                   No           4   
3                  No                No                   No           4   
4                  No                No                   No           4   

   Aggregate rating  Rating color Rating text Votes  
0               4.8    Dark Green   Excellent   314  
1               4.5    Dark Green   Excellent   591  
2               4.4         Green   Very Good   270  
3               4.9    Dark Green   Excellent   365  
4               4.8    Dark Green   Excellent   229  

[5 rows x 21 columns]

In [5]:
data.shape

(9551, 21)

In [6]:
data.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

# average cost for two nikalo

In [7]:
# STEP 1: jo columns nahi chahiye, wo hatao

In [8]:
data.drop(columns=['Restaurant ID','Is delivering now','Switch to order menu','Rating color','Rating text'], inplace=True)

In [9]:
data.shape

(9551, 16)

In [10]:
data['Country Code'].value_counts()

1      8652
216     434
215      80
214      60
30       60
189      60
148      40
208      34
14       24
162      22
94       21
191      20
166      20
184      20
37        4
Name: Country Code, dtype: int64

In [11]:
data=data[data['Country Code']==1]
#we are removing other countries

In [12]:
data.shape

(8652, 16)

In [13]:
data['City'].value_counts()

New Delhi       5473
Gurgaon         1118
Noida           1080
Faridabad        251
Ghaziabad         25
Ahmedabad         21
Guwahati          21
Lucknow           21
Bhubaneshwar      21
Amritsar          21
Pune              20
Nashik            20
Indore            20
Nagpur            20
Coimbatore        20
Aurangabad        20
Patna             20
Ludhiana          20
Surat             20
Kochi             20
Dehradun          20
Mangalore         20
Vizag             20
Vadodara          20
Goa               20
Puducherry        20
Kolkata           20
Bhopal            20
Varanasi          20
Jaipur            20
Kanpur            20
Agra              20
Mumbai            20
Chennai           20
Bangalore         20
Mysore            20
Allahabad         20
Ranchi            20
Chandigarh        18
Hyderabad         18
Secunderabad       2
Mohali             1
Panchkula          1
Name: City, dtype: int64

In [14]:
data=data[data['City'].isin(['New Delhi','Gurgaon','Noida','Faridabad'])]

In [15]:
data.shape

(7922, 16)

In [16]:
data.columns

Index(['Restaurant Name', 'Country Code', 'City', 'Address', 'Locality',
       'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Price range', 'Aggregate rating', 'Votes'],
      dtype='object')

In [17]:
data.drop(columns=['Restaurant Name','Country Code','Address','Locality','Locality Verbose','Currency'],inplace=True)

In [18]:
data.shape

(7922, 10)

In [19]:
data['Has Table booking'].replace({'Yes':1,'No':0},inplace=True)

In [20]:
data['Has Online delivery'].replace({'Yes':1,'No':0},inplace=True)

In [21]:
data.shape

(7922, 10)

In [22]:
data.corr()['Average Cost for two']

Longitude               0.071752
Latitude                0.070993
Average Cost for two    1.000000
Has Table booking       0.642966
Has Online delivery     0.076953
Price range             0.847985
Aggregate rating        0.328440
Votes                   0.299089
Name: Average Cost for two, dtype: float64

In [23]:
data.drop(columns=['Has Online delivery','Price range'],inplace=True)

In [24]:
data.shape

(7922, 8)

In [25]:
data.columns

Index(['City', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two',
       'Has Table booking', 'Aggregate rating', 'Votes'],
      dtype='object')

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7922 entries, 865 to 9112
Data columns (total 8 columns):
City                    7922 non-null object
Longitude               7922 non-null float64
Latitude                7922 non-null float64
Cuisines                7922 non-null object
Average Cost for two    7922 non-null int64
Has Table booking       7922 non-null int64
Aggregate rating        7922 non-null float64
Votes                   7922 non-null int64
dtypes: float64(3), int64(3), object(2)
memory usage: 557.0+ KB


In [27]:
#1 hot encoding
#categories mein divide karke in case of city
#delete last column

In [28]:
data['Cuisines'].value_counts()

North Indian                                                        901
North Indian, Chinese                                               474
Fast Food                                                           330
Chinese                                                             323
North Indian, Mughlai                                               313
Cafe                                                                251
Bakery                                                              212
North Indian, Mughlai, Chinese                                      194
Bakery, Desserts                                                    168
Street Food                                                         145
Pizza, Fast Food                                                    126
Chinese, Fast Food                                                  117
Mithai, Street Food                                                 116
Bakery, Fast Food                                               

In [29]:
a=data.groupby('Cuisines')['Average Cost for two'].mean().sort_values(ascending=False).reset_index()

In [30]:
a

Cuisines  Average Cost for two
0                Asian, Japanese, Korean, Thai, Chinese           7000.000000
1          North Indian, Chinese, South Indian, Italian           6000.000000
2       Malaysian, Thai, Kerala, Vietnamese, Sri Lankan           6000.000000
3           Chinese, Italian, Continental, North Indian           5000.000000
4                               Mediterranean, European           5000.000000
5                   North Indian, European, Continental           5000.000000
6                                       French, Italian           5000.000000
7                                      Seafood, Italian           5000.000000
8                  Finger Food, Italian, Middle Eastern           4700.000000
9                                      Spanish, Italian           4500.000000
10                  Continental, Italian, Mediterranean           4500.000000
11                  Mughlai, North Indian, South Indian           4500.000000
12          Continental, European, North Indian, French           4500.000000
13           Finger Food, Continental, Italian, Chinese           4400.000000
14                                      Malaysian, Thai           4200.000000
15                                          Thai, Asian           4000.000000
16                                Japanese, Thai, Sushi           4000.000000
17              Seafood, Chinese, Japanese, Sushi, Thai           4000.000000
18    North Indian, Continental, European, Chinese, ...           3800.000000
19                                       South American           3750.000000
20                                             European           3700.000000
21            Continental, North Indian, Italian, Asian           3600.000000
22                            Pizza, Salad, Finger Food           3500.000000
23                      Cafe, Continental, North Indian           3500.000000
24         Continental, Italian, American, North Indian           3500.000000
25    North Indian, Mediterranean, European, Asian, ...           3500.000000
26                      European, Italian, North Indian           3400.000000
27                                European, Continental           3275.000000
28     Continental, North Indian, European, Finger Food           3200.000000
29    Mediterranean, Continental, North Indian, Italian           3200.000000
...                                                 ...                   ...
1126                           Bakery, Fast Food, Pizza            200.000000
1127                     Bakery, Fast Food, Street Food            200.000000
1128                               Ice Cream, Beverages            200.000000
1129                                     Bakery, Mithai            200.000000
1130                                             Juices            187.500000
1131                                Beverages, Desserts            175.000000
1132                 Raw Meats, Fast Food, North Indian            175.000000
1133                                Street Food, Mithai            158.333333
1134                                Mithai, Street Food            155.172414
1135                                             Mithai            152.857143
1136                                        Street Food            150.482759
1137                               Chinese, Street Food            150.000000
1138                                   Bengali, Chinese            150.000000
1139                       South Indian, Pizza, Chinese            150.000000
1140                                  Beverages, Juices            150.000000
1141                             Ice Cream, Street Food            150.000000
1142                                    Mithai, Chinese            150.000000
1143                                  Juices, Beverages            150.000000
1144                       Street Food, Chinese, Mithai            150.000000
1145               North Eastern, North Indian, Chinese            15

In [31]:
data=data.merge(a,on="Cuisines")

In [32]:
data.drop(columns=['Cuisines'], inplace=True)

In [33]:
data.head()

City  Longitude   Latitude  Average Cost for two_x  Has Table booking  \
0  Faridabad  77.306640  28.490059                     250                  0   
1  New Delhi  77.049525  28.806199                     500                  0   
2  Faridabad  77.304776  28.490157                     500                  0   
3  Faridabad   0.000000   0.000000                     300                  0   
4  Faridabad  77.305698  28.471985                    1200                  1   

   Aggregate rating  Votes  Average Cost for two_y  
0               2.9      4              375.000000  
1               0.0      0              375.000000  
2               2.8     16              594.303797  
3               0.0      0              594.303797  
4               0.0      0              594.303797

In [34]:
data.rename(columns={'Average Cost for two_x':'cost','Average Cost for two_y':'cuisines'},inplace=True)

In [35]:
data.head()

City  Longitude   Latitude  cost  Has Table booking  Aggregate rating  \
0  Faridabad  77.306640  28.490059   250                  0               2.9   
1  New Delhi  77.049525  28.806199   500                  0               0.0   
2  Faridabad  77.304776  28.490157   500                  0               2.8   
3  Faridabad   0.000000   0.000000   300                  0               0.0   
4  Faridabad  77.305698  28.471985  1200                  1               0.0   

   Votes    cuisines  
0      4  375.000000  
1      0  375.000000  
2     16  594.303797  
3      0  594.303797  
4      0  594.303797

In [36]:
data.corr()['cost']

Longitude            0.071752
Latitude             0.070993
cost                 1.000000
Has Table booking    0.642966
Aggregate rating     0.328440
Votes                0.299089
cuisines             0.808274
Name: cost, dtype: float64

In [37]:
y=data.iloc[:,3].values

In [38]:
y

array([ 250,  500,  500, ...,  450, 1000,  450], dtype=int64)

In [39]:
y.shape

(7922,)

In [40]:
X=data.drop(columns=['cost']).iloc[:,:].values

In [41]:
X.shape

(7922, 7)

In [42]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [43]:
X[:,0]=encoder.fit_transform(X[:,0]) #lABEl encode kar diya... for city

In [44]:
X

array([[0, 77.3066401, 28.4900591, ..., 2.9, 4, 375.0],
       [2, 77.04952508, 28.80619877, ..., 0.0, 0, 375.0],
       [0, 77.304776, 28.490156699999996, ..., 2.8, 16,
        594.3037974683544],
       ...,
       [3, 77.3648332, 28.5971027, ..., 3.5, 105, 450.0],
       [3, 77.32321292, 28.567750899999997, ..., 0.0, 0, 1000.0],
       [3, 77.32530809999999, 28.5671503, ..., 2.0, 161, 450.0]],
      dtype=object)

In [45]:
X[:,0]

array([0, 2, 0, ..., 3, 3, 3], dtype=object)

In [46]:
X.shape

(7922, 7)

In [47]:
from sklearn.preprocessing import OneHotEncoder
oencoder=OneHotEncoder(categorical_features=[0])

In [48]:
X=oencoder.fit_transform(X).toarray()

E:\anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
E:\anaconda\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [49]:
X.shape

(7922, 10)

In [50]:
X[:,0:4]

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [51]:
X=X[:,1:]

In [52]:
X.shape

(7922, 9)

In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=7)

In [54]:
from sklearn.linear_model import LinearRegression
regressor1=LinearRegression()

In [55]:
regressor1.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [56]:
from sklearn.metrics import r2_score

In [57]:
y_pred=regressor1.predict(X_test)

In [58]:
r2_score(y_test,y_pred)*100

69.45487835658291